version: '3'

services:
  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    command: npm run dev
    stdin_open: true
    tty: true
    volumes:
      - ./app/src:/usr/src/app/src

  api:
    command: npm run dev
    environment:
      - MODE=development
    volumes:
      - ./api/src:/usr/src/app/src

  db:
    ports:
      - "27017:27017"