FROM node:12.18.3-alpine3.10

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install && npm install -g serve

COPY . .

# Скопировать файл serve.json
COPY ./serve.json /usr/src/app/dist

RUN npm run build